- name: Install Filebeat
  apt:
    name: filebeat
    state: present
    update_cache: true

- name: Configure Filebeat for Magento logs
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Enable and start Filebeat
  systemd:
    name: filebeat
    enabled: true
    state: started
